config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
	resources :meals do
    resources :comments
  end



  resources :ingredients do
    collection do
      patch :sort
    end
  end

  resources :meals do
    member do
      put "like", to: "meals#upvote"
    end
  end

  get 'pages/info'
  get 'pages/contact'
  get 'pages/faq'
  resources :comments
  root to: redirect('/meals')
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :meals
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meal , optional: true
  belongs_to :user , optional: true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :meal
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :meal
end

app/models/meal.rb
# frozen_string_literal: true

class Meal < ApplicationRecord
	acts_as_votable
	has_many :comments
	has_many :ingredients
	has_many :directions
	accepts_nested_attributes_for :ingredients,
																reject_if: proc { |attributes| attributes['name'].blank? },
																allow_destroy: true
	accepts_nested_attributes_for :directions,
																reject_if: proc { |attributes| attributes['name'].blank? },
																allow_destroy: true
	validates :name, :description, :picture, presence: true

	belongs_to :user
	belongs_to :category
	mount_uploader :picture, PictureUploader



	def self.search_by(search_term)
		where ("LOWER(name) LIKE :search_term"), search_term: "%#{search_term.downcase}"
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :meals
	has_many :comments
	has_many :ingredients
	has_many :procedures
	mount_uploader :picture, PictureUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  include Gravtastic
	gravtastic :secure => true,
              :size => 500
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
		include Pagy::Backend
		
	  before_action :configure_permitted_parameter, if: :devise_controller?

	  protected
	  def configure_permitted_parameter
	  	devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:first_name, :last_name, :user_name,:about, :birthday, :email, :password, :remember_me)}
	  	devise_parameter_sanitizer.permit(:sigin_in){|u| u.permit(:email, :password, :remember_me)}
	  	devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:first_name, :last_name, :user_name,:about, :birthday, :email, :password,:current_password, :remember_me)}

	  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build
    @meal = Meal.find(params[:meal_id])
    @comment = @meal.comments.create(params[:comment].permit(:name, :body))
    redirect_to meal_path(@meal)
  end
end

app/controllers/meals_controller.rb
# frozen_string_literal: true

class MealsController < ApplicationController
  before_action :set_meal, only: [:show, :edit, :update, :destroy, :upvote]

  # GET /meals
  # GET /meals.json
  def index
    if params[:category].blank?
    @pagy, @meals = pagy(Meal.all)
    else
      @category_id = Category.find_by(name: params[:category]).id
      @meals = Meal.where(:category_id => @category_id)
    end
    if params[:search]
      @search_term = params[:search]
      @meals = @meals.search_by(@search_term)
    end
  end


  # GET /meals/1
  # GET /meals/1.json
  def show
    @comments = @meal.comments.all
    @comment = @meal.comments.build
  end

  # GET /meals/new
  def new
   @meal = current_user.meals.build
   @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  # GET /meals/1/edit
  def edit
    @categories= Category.all.map{ |c| [c.name, c.id] }
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = current_user.meals.build(meal_params)
    @meal.category_id = params[:category_id]
    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    @meal.category_id = params[:category_id]
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @meal.upvote_by current_user
    redirect_to meal_path(@meal)
  end
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meal_params
    params.require(:meal).permit(:name, :description, :picture, :category_id, ingredients_attributes: [:id, :name, :_destroy], directions_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def contact
  end
  def faq

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = User.find(params[:id])
    @user_meals = @user.meals

    u = User.new
  end

  def meal_params
    params.require(:meal).permit(:description, :username, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
# frozen_string_literal: true

module MealsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.meal, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %></p>
 	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@meal, @meal.comments.build]) do |f| %>
<style>
		 input[type=text] {
			 width: 100%;
			 padding: 12px 20px;
			 margin: 8px 0;
			 display: inline-block;
			 border: 1px solid #ccc;
			 border-radius: 4px;
			 box-sizing: border-box;
		 }
		 #comment_body {
			 width: 100%;
			 padding: 12px 20px;
			 margin: 8px 0;
			 display: inline-block;
			 border: 1px solid #ccc;
			 border-radius: 4px;
			 box-sizing: border-box;
		 }
		 #form {
		 border-radius: 5px;
		 background-color: #f2f2f2;
		 padding: 20px;
		 }
	 </style>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<br>
	<%= f.label :body %><br>
	<%= f.text_area :body %><br>
	<br>
	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
  <head>

   <title>Meals</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'false' %>
    <%= javascript_include_tag 'application','data-turbolinks-track' => true %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>

   <div class="page-header">
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
     <div class="container-fluid">

      <div class="navbar-header">
       <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
       <span class="sr-only">Toggle navigation</span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       <span class="icon-bar"></span>
       </button>
       <a class="navbar-brand" href="/">Main Menu</a>
      </div>

      <div class="collapse navbar-collapse">
       <ul class="nav navbar-nav">
        <li><a href="/meals/new">New Recipe</a></li>
        <li><a href="/pages/contact">Contact Us</a></li>

       </ul>


       <p class="navbar-text pull-right">
        <% if user_signed_in? %>
        <%= image_tag current_user.gravatar_url, :class => "gravatar" %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to current_user.first_name, current_user%> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link navbar-text navbar-right'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
       </p>
      </div>
    </div>
   </nav>
  </div>

  <div>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>


    <div class="w3-container-fluid">
      <div class="w3-row">
        <div class="bg">
        <div class="w3-container w3-center">
          <div class="splash__brand">
            <%= image_tag "Logo.png", class: "splash__brand__logo", width: '150px', height: '150px' %>
          </div>
          <h2 style="color: white;"> You can Search Your Recipe in Here!!!
          <a><%= form_for "",url: meals_path, role: "search" , method: :get do %>
          <%= text_field_tag :search, @search_tearm,placeholder: "MEAL Name....." %>
          <% end %></a>
          </h2>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Category
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
              <li class="<%= 'active' if params[:category] == category.name %>">
                <%= link_to category.name, meals_path(category: category.name), class: "link" %>
              </li>
                <% end %>
            </ul>
          </div>
         </div>
      </div>
    </div>
  </div>
  <%= yield %>

  <footer class="container-fluid text-center" style="  background-color: #ccccb3;color: black;padding: 15px;       margin-top: 15px;">
        <div>
       Our Recipes Website is Offering you above these Orders.
        <br>
        No 1509, 15 Floor,Sakura Tower<br>
        yangonpress@gmail.com<br>
        Ph: 0918848225 <br>
        <div>
            <div class="row">
              <div class="col-sm-4">
                <a href="/juices"><h5>Juice</h5></a>
                We offering You These Orders<br>
                We admit that the Food are really good Quality <br>
              </div>
              <div class="col-sm-4">
                <a href="/meals"><h5>Meals</h5></a>
                <%= Time.now.year %><br>
                We offering You These Orders<br>
                We admit that the  are Juices really good Quality and Healthy for you.<br>
              </div>
              <div class="col-sm-4">
                <h5>Social</h5>
                <a href="https://www.facebook.com/"><p>Facebook</p></a>
                <a href="https://www.instagram.com/">
                  <p>Instagram</p>
                </a>
                <a href="https://www.google.com/"><p>Google</p></a>

              </div>
            </div>
          </div>
        </div>
      </footer>
 </body>
</html>

app/views/meals/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove Step", f, class: "btn btn-default form-button" %>
  </div>
</div>

app/views/meals/_form.html.erb

  <%= simple_form_for @meal, html: { multipart: true } do |f| %>
    <% if @meal.errors.any? %>
      <div id="errors">
        <p>
          <%= @meal.errors.count %>
          Prevented this meal froms saving
        </p>
        <ul>
          <% @meal.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="panel-body">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
      <%= f.input :name, input_html: { class: 'form-control' } %>
      <%= f.input :description, input_html: { class: 'form-control' } %>
      <%= f.file_field :picture, id: :meal_picture %>

      <div class="row">


              <div class="col-md-6">
                <h3>Ingredients</h3>
                <div id="ingredients">
                  <%= f.simple_fields_for :ingredients do |ingredient| %>
                    <%= render 'ingredient_fields', f: ingredient %>
                  <% end %>
                  <div class="links">
                    <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
                  </div>
                </div>
              </div>


        <div class="col-md-6">
          <h3>Directions</h3>
          <div id="directions">
            <%= f.simple_fields_for :directions do |direction| %>
              <%= render 'direction_fields', f: direction %>
            <% end %>
            <div class="links">
              <%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
            </div>
          </div>
        </div>


      </div>
    </div>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

app/views/meals/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/meals/edit.html.erb
<div class="container">
  <h1>Editing Meal</h1>

  <%= render 'form', meal: @meal %>
  <br>
  <button type="button"><%= link_to 'Show', @meal %></button> |
  <button type="button"><%= link_to "Back", root_path %></button>
</div>

app/views/meals/index.html.erb
<div class="w3-container w3-padding-32" id="recipes">
    <h2 class="w3-border-bottom w3-border-grey w3-padding-16" style="color: brown; text-align: center;" > <b>Here Are Our Meals
    </b></h2>
</div>



  <div class="container">
    <div class="row">
      <h1 class="current-category"><%= params[:category] %></h1>

      <% if @meals.count == 0 %>

        <h1>There are no meals currently in this category</h1>

      <% else %>

      <div class="row">
        <% @meals.each do |meal| %>
          <div class="col-md-4">
            <div class="recipe">
              <div class="image_wrapper">
                <%= link_to meal do %>
                  <%= image_tag meal.picture.url, width: '250px', height: '250px' if meal.picture.present? %>
                <% end %>
              </div>
              <h2>
                <%= link_to meal.name, meal %>
              </h2>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    <%end %>
    <%== pagy_bootstrap_nav(@pagy).html_safe %>
  </div>

app/views/meals/new.html.erb
<div class="container">
<h1 style="color: #4c0080;">You can create meal from here Easily!!</h1>

<%= render 'form', meal: @meal %>

<button type="button"><%= link_to "Back", root_path %></button>
</div>

app/views/meals/show.html.erb
<br>
<div class="container">
  <div class="row">

    <div class="col-md-4">
      <%= image_tag(@meal.picture_url, width: '350px', height: '350px') if @meal.picture.present? %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @meal.name %>
        </h1>
        <h4>
          Category: <%= @meal.category.name %>
        </h4>
        <h5>
          Posted by <%= @meal.user.email %> <%= time_ago_in_words(@meal.created_at) %> ago.
        </h5>
        <p class="description">
          <%= @meal.description %>
        </p>
        <%= link_to like_meal_path(@meal), method: :put, class: "btn btn-default" do %>
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <%= @meal.get_upvotes.size %>
        <% end %>
      </div>
    </div>
  </div>
<!-- ///////////////////////////////////////////////////////////////// -->

  <br>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @meal.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  <!-- ////////////////////////////////////////////////////// -->
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @meal.directions.each do |direction| %>
            <li>
              <%= direction.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!-- /////////////////////////////////////////// -->

  <div class="row">
    <div class="col-md-8">
      	<div id="comments">
      		<h2><%= @meal.comments.count %> Comments</h2>
      		<%= render @meal.comments %>
        </div>
        </div>
        <div class="col-md-4">
          <h3>Add a comment:</h3>
          <%= render "comments/form" %>
        </div>

  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
            <button type="button"><%= link_to "Back", root_path %></button>
            <% if user_signed_in? %>
              <%if @meal.user == current_user%>
              <button type="button"><%= link_to 'Edit', edit_meal_path(@meal)%> </button>
              <button type="button"><%= link_to 'Destroy', meal_path(@meal), data: { confirm: 'Are you sure?' }, method: :delete %></button>
              <% end %>
            <% end %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<main role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <div class="container">
      <h1 class="display-3">Welcome to ours myanmar food ever</h1>
      <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
      <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more »</a></p>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="row">
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
      <div class="col-md-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <p><a class="btn btn-secondary" href="#" role="button">View details »</a></p>
      </div>
    </div>

    <hr>

  </div> <!-- /container -->

</main>

app/views/pages/faq.html.erb
<!DOCTYPE html>
	<html>
		<head>
			<title>Help Center</title>
			<h3 style="color: brown;">Frequently Ask Question</h3>

			<body>
				<p>This page will show you how to add meal and see your comments.</p>

				<p>Cras condimentum purus sit amet neque pellentesque faucibus. Etiam venenatis iaculis quam, et porta mauris congue cursus. Quisque nec posuere neque. Donec ornare purus eget pharetra placerat. Cras tempor odio eget ex pharetra, nec ultrices arcu iaculis. Nunc egestas lacus eu pulvinar mattis. Phasellus accumsan elit eget enim lacinia posuere. Ut in tempus ipsum, sit amet tempus mi. Phasellus fermentum turpis vel euismod cursus. Nullam non vestibulum lacus. Praesent mauris augue, tincidunt eget vulputate a, posuere vitae orci. Pellentesque ac ante tellus.</p>

				<p>Nulla facilisis non mi vitae fringilla. Donec efficitur eleifend ullamcorper. Duis commodo congue lectus sed imperdiet. Ut nec placerat lacus, ac convallis mauris. Ut suscipit, augue a faucibus rutrum, lectus risus feugiat nunc, vel varius enim mauris quis massa. Suspendisse scelerisque, erat eu molestie mattis, ligula mauris semper tortor, sit amet faucibus nisl leo vitae neque. Cras semper nibh nec efficitur pellentesque. Cras a pretium nisi, sit amet convallis mi.</p>

				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec tempor consectetur molestie. In consequat sem imperdiet, interdum lacus et, volutpat nisl. Duis dignissim consectetur facilisis. Quisque auctor nulla quis ante suscipit, iaculis laoreet lorem hendrerit. Vivamus pulvinar sem eget lorem ornare, maximus dictum justo auctor. Sed congue ultricies fringilla. Phasellus lacinia neque at tortor convallis ornare. Nunc quis est id ipsum accumsan viverra. Donec sed condimentum urna. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris massa tortor, imperdiet vel ante nec, finibus posuere mi. Fusce mattis nisi at lacus auctor posuere. In augue quam, suscipit lacinia maximus non, euismod eget eros. Ut suscipit cursus pretium. Maecenas lacus tellus, convallis nec maximus sit amet, lobortis at urna.</p>
			</body>
	</html>

app/views/pages/info.html.erb
<h1>Information!</h1>
<p>
Microdosing master cleanse yr hoodie disrupt artisan leggings banjo banh mi post-ironic art party succulents. Af you probably haven't heard of them helvetica hammock disrupt, vice hashtag tumblr aesthetic slow-carb four dollar toast poutine forage synth. Fingerstache chia YOLO lo-fi shaman yr street art hammock normcore vice enamel pin cliche williamsburg selfies truffaut. Tofu fanny pack plaid polaroid tattooed, before they sold out poke vaporware gochujang tilde leggings 8-bit banjo.

Gluten-free echo park synth literally freegan locavore. Chia distillery authentic, organic narwhal PBR&B hella church-key flannel everyday carry asymmetrical. Bicycle rights vice PBR&B tofu kitsch prism cloud bread hell of organic humblebrag. Asymmetrical art party DIY williamsburg, franzen forage godard lomo biodiesel gentrify. Hashtag cardigan glossier, woke truffaut neutra messenger bag gastropub tilde hammock mumblecore butcher direct trade selfies.

Tofu asymmetrical you probably haven't heard of them art party swag, literally polaroid paleo air plant yr. Chillwave PBR&B retro selvage irony ethical four dollar toast. Activated charcoal poutine iPhone, hammock cornhole schlitz meditation scenester raclette etsy fanny pack pug. Meh ramps street art, tofu farm-to-table meditation gastropub affogato four dollar toast brooklyn coloring book.

Selvage scenester swag, umami kickstarter ethical DIY photo booth. Cloud bread lumbersexual ramps distillery blog palo santo bushwick umami narwhal put a bird on it flexitarian forage retro. Subway tile meh disrupt taiyaki everyday carry. Prism fam blog lyft bespoke, cardigan salvia cronut vegan. Irony beard glossier hella salvia affogato. YOLO lo-fi try-hard, XOXO keytar drinking vinegar williamsburg leggings yr humblebrag kogi four dollar toast sartorial.</p>

app/views/users/show.html.erb
<div class="profile">
   <h3>About Me</h3>
   <hr>
    <%= image_tag current_user.gravatar_url, :class => "gravatar-show" %>
      <h4>Hello! Nice to meet you!!!</h4>
      <h5> My Full name: <%= @user.first_name %> <%= @user.last_name %></h5>
      <h5>Birthday :<%= @user.birthday %></h5>    d
      <p><%= @user.about %></p>
      <h2>Meals that have been created!!</h2>

      <% if @user_meals.count == 0 %>

        <h1>You Haven't create any recipe yet.</h1>

      <% else %>
        <div class="row">
            <% @user_meals.each do |meal|%>
            <div class="col-md-4">
              <div class="recipe">
                <div class="image_wrapper">
                  <%= link_to meal do %>
                    <%= image_tag meal.picture.url, width: '250px', height: '250px' if meal.picture.present? %>
                  <% end %>
                </div>
                <h2>
                  <%= link_to meal.name, meal %>
                </h2>
              </div>
            </div>
              <%end%>
          </div>
          <%end%>
      </div>